### ISSUE TITLE
Use image-webpack-loader instead of `file-loader` for images?

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#104]
The [image-webpack-loader](https://github.com/tcoopman/image-webpack-loader) will optimize images, should we use it instead of `file-loader`?

```js
{
  test: /\.(png|svg|jpg|jpeg|gif|ico)$/,
  exclude: [/fonts/, /node_modules/],
  use: `file-loader?name=${outputImages}`,
}
```

?

**Comment by iruzevic** [comment]
there have been issues with https://github.com/tcoopman/image-webpack-loader in the past. 

This loader has not been updated for several months, and the banner states that it is out of date.

we should check it out. Maybe version 3.1

**Comment by dingo-d** [comment]
Wasn't aware of the issues. I agree with pushing this back to later version :+1:

**Comment by IvanGrginovInf** [comment]
@dingo-d @iruzevic Is this still relevant?

Personally I think it's not worth it (we should be loading most of our images through WordPress's media library anyway, the few that we're loading as `static` assets can be optimized manually if needed).

Also https://github.com/tcoopman/image-webpack-loader is reporting issues on some Mac versions when you don't have some library installed, I'd rather if we not add a new potential fail-point during setup for, what I believe is, almost no added benefit.

**Comment by iruzevic** [comment]
Agreed you can close this
