### ISSUE TITLE
error logs for sass lint

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-boilerplate#112]
Building assets doesn't throw error even if an invalid map variable OR key is provided as map-get parameter.

**Comment by dingo-d** [comment]
We didn't include this in the 3.0.1 it seems, I'm pushing it for 4.0.0 milestone.

**Comment by iruzevic** [comment]
this is transfered to https://github.com/infinum/eightshift-frontend-libs and fixed
