### ISSUE TITLE
Test autoloader with excludes

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#119]
We should test if this is working.

```json
"autoload": {
    "exclude-from-classmap": ["/vendor/", "/node_modules/"],
    "classmap": [
      "."
    ]
  },
```

I tested it on my plugin and it did the trick, but in the end I didn't use it since I needed some libraries from vendor autoloaded. Originally will pick up all the classes in the current directory excluding the vendor ones.

**Comment by iruzevic** [comment]
This is working on a plain boilerplate example. Should we add it to to the version 3?
@dingo-d @IvanGrginovInf

**Comment by dingo-d** [comment]
Depends on the library. Some use custom autoloader, some use PSR2. In my specific case I needed to have some libraries autoloaded via classmap iirc so that option wasn't working.

This should be explored in more detail, for the time being I think the best thing would be to test this with and without vendor and see if everything is working as it should.

**Comment by IvanGrginovInf** [comment]
@dingo-d @iruzevic  Is this still relevant now we're really public with Boilerplate?

```json
"autoload": {
    "exclude-from-classmap": ["/vendor/", "/node_modules/"],
    "classmap": [
      "."
    ]
  },
```

> In my specific case I needed to have some libraries autoloaded via classmap iirc so that option wasn't working.

If we exclude `vendor` by default, this right here will make some user's life somewhere really complicated in trying to debug why his 3rd party library isn't working in his boilerplate project.

Excluding `node_modules` is kinda weird as I would expect minimal number of `.php` files in there (if any).

Also what is the real benefit here? Smaller classmap files I assume? PHP is pretty traversing arrays, I doubt we'd be shaving more than a couple of ms of load time at best.

**Comment by dingo-d** [comment]
`node_modules`can be removed, the `vendor` I'm not 100% sure. Every lib should take care of autoloading, and if the lib has the classmap autoloader, it should be added to your own if you use it in the project afaik.

**Comment by iruzevic** [comment]
we switched to psr-4
