### ISSUE TITLE
Accessibility tests

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#120]
Once we merge the zero config PR, we should run a lighthouse check, and see what issues are present. 

One of the thing that we should see if we can test is how the boilerplate fares against accessibility issues (using keyboard etc.).

We have a minimal set of templates, but we should still see how they can be improved.

Also, we could give good examples in the documentation @gabriel-glo how to make the theme more accessible.

For reference, you can check the code from [twentynineteen](https://github.com/WordPress/twentynineteen) and [_s](https://github.com/Automattic/_s) themes and how they are handling the accessibility stuff.

**Comment by dingo-d** [comment]
https://make.wordpress.org/themes/2019/07/14/how-to-add-and-test-skip-links/

A useful link for implementing skip links.

Also this link is useful: https://make.wordpress.org/themes/handbook/review/accessibility/

**Comment by iruzevic** [comment]
no need here

**Comment by dingo-d** [comment]
> no need here

You mean we'll move this to frontend libs, right?
