### ISSUE TITLE
Manifest json

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-boilerplate#128]
Pozdrav,
imam problem sa manifest.json.

Kada pokrenem npm start napravi dobar manifest json u kojem se nalazi jquery. 
{
  "application.css": "//wp-content/themes/test/skin/public/application.css",
  "application.js": "//wp-content/themes/test/skin/public/application.js",
  "applicationAdmin.css": "//wp-content/themes/test/skin/public/applicationAdmin.css",
  "applicationAdmin.js": "//wp-content/themes/test/skin/public/applicationAdmin.js",
  "vendors.js": "//wp-content/themes/test/skin/public/vendors.js",
  "jquery.min.js": "//wp-content/themes/test/skin/public/jquery.min.js",
  "logo.svg": "//wp-content/themes/test/skin/public/logo.svg"
}

Nakon toga  napravim bilo kakvu izmjenu u *.js manifest mi izgleda ovako
{
  "application.css": "//wp-content/themes/test/skin/public/application.css",
  "application.js": "//wp-content/themes/test/skin/public/application.js",
  "applicationAdmin.css": "//wp-content/themes/test/skin/public/applicationAdmin.css",
  "applicationAdmin.js": "//wp-content/themes/test/skin/public/applicationAdmin.js",
  "vendors.js": "//wp-content/themes/test/skin/public/vendors.js",
  "logo.svg": "//wp-content/themes/test/skin/public/logo.svg"
}

Vidim da nedostaje redak sa jquery...jem

**Comment by marijang** [comment]
Izgleda da u webpack.config.js line 144 
Iz 
new ManifestPlugin()
u
new ManifestPlugin({seed: {}}),

popravlja problem....

**Comment by marijang** [comment]
Inace odlican posao. 
Zanima me hoce li nekada biti verzija sa ukljucenim recimo 
1. React
2. Vue
3. Angular

npr prilikom instalacije odaberes s cime ces raditi.

Hvala
Lp

**Comment by dingo-d** [comment]
Hvala na ukazanom bugu, kolega će se bacit na ispravak 🙂 

Iskreno nismo planirali dodavanje front end frameworka, kad god u firmi radimo s njima, obično radimo kompletno decoupled, gdje u pluginu radimo s REST APIjem, a tema nam je prazna.

**Comment by gabriel-glo** [comment]
Testirao sam sa dodavanjem seed option-a u inicializaciju ManifestPlugin i navedeni problem je rijesen.

https://www.npmjs.com/package/webpack-manifest-plugin#optionsseed

**Comment by IvanGrginovInf** [comment]
Fix izgleda da radi, još ću malo testirati pa ide gore.

**Comment by marijang** [comment]
hm....onda bi bilo cool imati primjer toga:D

**Comment by iruzevic** [comment]
ovo je fixano tnx
