### ISSUE TITLE
After npm start - redirected to : www.namebroker.co.uk

### ISSUE THREAD

**Issue by PatriceBois** [infinum/eightshift-boilerplate#151]
Hi,

After i run the install, i run the npm start dans my browser sync redirect me to : namebroker.co.uk

my proxy url is : proxyUrl: 'dev.provalis.com',

**Comment by gabriel-glo** [comment]
Hi,

this is happening because dev.provalis.com is already a registered domain.
Please change proxyUrl from .com to something like .test or .local and it
will work.

**Comment by IvanGrginovInf** [comment]
You need to use your **local** development url, not a url that's already live (which is I'm assuming, your staging site). BrowserSync can't do anything with URLs that are already live.

It needs the URL that's setup in your `/etc/hosts` file by whatever tool you use for local development. If your tool doesn't do this out of the box (such as MAMP), you'd need to setup nginx / apache and your hosts file yourself.

You can also develop without browsersync, just run `npm start` in a terminal and leave it be and keep developing as you normally would.

**Comment by PatriceBois** [comment]
Ok thanks guys... i will not use the proxy for now... i just try to send all file on my staging server and i got this error : 

Fatal error: Uncaught TypeError: Return value of Eightshift_Libs\Core\Main::register() must be an instance of Eightshift_Libs\Core\void, none returned in /home/siteint/public_html/provalist/wp-content/themes/provalis/vendor/infinum/eightshift-libs/src/class-main.php:54 Stack trace: #0 /home/siteint/public_html/provalist/wp-content/themes/provalis/functions.php(53): Eightshift_Libs\Core\Main->register() #1 /home/siteint/public_html/provalist/wp-settings.php(499): include('/home/siteint/p...') #2 /home/siteint/public_html/provalist/wp-config.php(90): require_once('/home/siteint/p...') #3 /home/siteint/public_html/provalist/wp-load.php(37): require_once('/home/siteint/p...') #4 /home/siteint/public_html/provalist/wp-blog-header.php(13): require_once('/home/siteint/p...') #5 /home/siteint/public_html/provalist/index.php(17): require('/home/siteint/p...') #6 {main} thrown in /home/siteint/public_html/provalist/wp-content/themes/provalis/vendor/infinum/eightshift-libs/src/class-main.php on line 54

**Comment by IvanGrginovInf** [comment]
Did you run `composer -o dump-autoload` on the staging servrer?

**Comment by IvanGrginovInf** [comment]
Nvm my previous comment, which php version are you running on the server? (and which one locally?)

You need to have `7.1` or newer with this boilerplate version.

Alternatively you can either update `eightshift-libs` composer package (we removed the `: void` typehinting in the latest develop version - this prevented the code from working on `7.0`) and remove all `: void` from boilerplate's code.
