### ISSUE TITLE
THEME_NAME constant is not changed during search replace script

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#153]
I've set up a theme locally using the `npx` script and the `\define( 'THEME_NAME', 'infinum' );` was left in my `functions.php` file.

I guess this will be fixed in the `eightshift-scripts`?

EDIT:

Found `INF_ASSETS_MANIFEST` as well...

**Comment by IvanGrginovInf** [comment]
Will fix after we're done messing with the theme as a result of moving towards `4.0.0`.

**Comment by dingo-d** [comment]
Also, the folder that was created for my theme was created using underscores: `theme_name`, and assets are pulled from dash separated folder: `theme-name`, so I'm getting errors on the front.

**Comment by iruzevic** [comment]
this is no longer valid
