### ISSUE TITLE
Missing priority in menu registration causes menu locations not to be registered

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#154]
I reckon that because there are lot's of places where `after_setup_theme` hook is used, there could be some weird conflict we oversaw. This causes menus not to be registered. 

I had to add

```php
add_action( 'after_setup_theme', [ $this, 'register_menu_positions' ], 11 );
```

in `class-menu.php` in order for the menu to be properly registered. There seem to be 5 matches where this hook is used, one of them is in the libs, so maybe the libs one could have a lower priority (since it kinda needs to be executed first).

**Comment by iruzevic** [comment]
this is fixed
