### ISSUE TITLE
Broken Link in Readme

### ISSUE THREAD

**Issue by thomasmalley** [infinum/eightshift-boilerplate#161]
The link (within the README.md) to the Plugin Boilerplate leads to 404 Page on Github. I wasn't able to find the new location of the repository. Does it still exist somewhere? Thank you so much for this collection!

**Comment by dingo-d** [comment]
Hi @thomasmalley!

We should probably remove that as we are still working on the plugin boilerplate (it's private so only people in our organisation can access it).

Once we have it ready, we'll put this back in the readme. 

Thanks for notifying us 👍

**Comment by thomasmalley** [comment]
Awesome!

**Comment by iruzevic** [comment]
tnx this is fixed. and we will be rolling out plugin for version 4.2.0
