### ISSUE TITLE
String must be compatible with Eightshift_Libs\Blocks\Renderable_Block

### ISSUE THREAD

**Issue by emisrw** [infinum/eightshift-boilerplate#182]
Hi!
I have problem with fresh instalation wordpress and your awesome template. 
After successful instalation using npx create-wp-project i got an error : 

`Fatal error: Declaration of Eightshift_Libs\Blocks\Blocks::render(array $attributes, $inner_block_content): string must be compatible with Eightshift_Libs\Blocks\Renderable_Block::render(array $attributes, string $content): string in /Users/matt/Desktop/serwer/newant/wp-content/themes/anttheme/vendor/infinum/eightshift-libs/src/blocks/class-blocks.php on line 23`

Environment :

* PHP version: 7.1.23 
* Composer version 1.9.0
* Node version: v11.3.0
* Wordpress version: 5.2.4
* Operating System : IOS

**Comment by iruzevic** [comment]
I have pushed a new version for [Eightshift_Libs](https://github.com/infinum/eightshift-libs/releases/tag/v2.0.2).

You should go to you boilerplate composer.json change infinum/eightshift-libs to "^2.0.2" and in terminal run "composer update".
