### ISSUE TITLE
Test on WordPress 5.3

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-boilerplate#184]
We should test if everything works ok on WordPress 5.3

**Comment by IvanGrginovInf** [comment]
Setup (installation) works just fine. Block controls and the entire Gutenberg editor...not so much. See attached video for what happens on a new page:

[https://drive.google.com/file/d/1-auSSONlB5yHNpl81dJn2cAAwP8ncYIN/view?usp=sharing](https://drive.google.com/file/d/1-auSSONlB5yHNpl81dJn2cAAwP8ncYIN/view?usp=sharing)

**Comment by iruzevic** [comment]
Some corrections are done but it looks ok on 5.3 now
