### ISSUE TITLE
BrowserSync not working with xampp

### ISSUE THREAD

**Issue by jesusrodrz** [infinum/eightshift-boilerplate#187]
## Current Behavior

I've create a site with xampp in localhost/aerolinea/ and configure the projecturl with that url but browsersync do not connect, i've tried adding the port 80 to the url but result the same and changing the default port of xampp dosent work nether 
I don't know if there is anything i0m doing wrong or if the problem is my sever configuration(the default with the instalation)

Browsersycn serves the file of my theme at localhost:3000/ but not the site
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* PHP version:
* Development environment: XAMPP  v3.2.4 
* Server type: Apache
* Operating System and version: win 10

**Comment by iruzevic** [comment]
We have updated the lib with some fixes, please update to the latest release and see if it helps:

```
npm i @eightshift/frontend-libs
```
