### ISSUE TITLE
all default blocks missing

### ISSUE THREAD

**Issue by yangkennyk** [infinum/eightshift-boilerplate#191]
I'm new to this boiler plate and trying to understand how it works and it doesn't seem like there's a ton of documentation on it.

Currently when I install the boiler plate, all the default wordpress blocks are gone. is that standard?

The width of the editor is also extends out of the window.

![image](https://user-images.githubusercontent.com/6680040/73141852-8b7fe000-4056-11ea-86b3-74120ecd5253.png)

**Comment by iruzevic** [comment]
Hi yes we are working on a documentation very hard an it will be out as soon as possible. 
In the meantime yes by default we have disabled all core block (we plan to remove that hook in the future). 

To return all default blocks follow this steps:
1. Create new class in `src>blocks` folder and call it `class-blocks.php`
2. Add something like this:
```php
<?php
/**
 * Blocks class used to define configurations for blocks.
 *
 * @since   1.0.0
 * @package Eightshift_Boilerplate\Blocks
 */

namespace Eightshift_Boilerplate\Blocks;

use Eightshift_Libs\Blocks\Blocks as Lib_Blocks;

/**
 * Blocks class.
 */
class Blocks extends Lib_Blocks {

  /**
   * Register all the hooks
   *
   * @since 1.0.0
   *
   * @return void
   */
  public function register() {
    parent::register();

    remove_filter( 'allowed_block_types', [ $this, 'get_all_blocks_list' ] );
  }
}

```
3. In `src>class-main.php` change `Lib_Blocks\Blocks::class => [ Config::class ],` with your project class.
4. Run in terminal `composer dump-autoload`

-------------
Yes we have removed some native spacing and padding around the blocks in the editor so we can have more similar layout in the editor and frontend. To remove this go to `src>blocks>assets>styles>application-blocks-editor.scss` and remove:
```
@import 'EighshiftEditorStyleOverride';
```

-------------
In general we are not working with core block using this boilerplate but we create our own blocks. In the future we plan to make boilerplate more in line with core blocks

**Comment by gabriel-glo** [comment]
@iruzevic This was fixed in more recent versions of the boilerplate and libs?

**Comment by iruzevic** [comment]
yes we have removed this condition in the latest version of eightshift-libs you should see all the blocks

**Comment by IvanGrginovInf** [comment]
Closing issue as this was fixed.
