### ISSUE TITLE
CSS hot reload

### ISSUE THREAD

**Issue by emisrw** [infinum/eightshift-boilerplate#193]
Hello, is there any possibility to enable hot replacement for css? BrowserSync refresh page and loses time.

**Comment by gabriel-glo** [comment]
Hi @emisrw,
we had an implementation of hot loading CSS in older versions of boilerplate, but it wasn't working the same way as BrowserSync works with Gulp. 

You can still add your custom webpack config for BrowserSync by extending the base configuration in https://github.com/infinum/eightshift-boilerplate/blob/develop/webpack.config.js
