### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-boilerplate#220]
Hey how to add woocommerce support?

I added 
/src/woo/class-woo.php

i get
Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition: Entry "Bit\Woo\Woo" cannot be resolved: the class doesn't exist Full definition: Object ( class = #UNKNOWN# Bit\Woo\Woo lazy = false ) in /Applications/MAMP/htdocs/test/wp-content/themes/bit/vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php:18 Stack trace: #0

I add in in class-main.php

use Bit\Woo;
....
// Woo.
Woo\Woo::class,

and woo class

declare( strict_types=1 );

namespace Bit\Menu;

use Eightshift_Libs\Core\Service;

/**
 * Class Menu
 *
 * @since 1.0.0
 */
class Woo implements Service {

   /**
   * Register all the hooks
   *
   * @return void
   *
   * @since 4.0.0
   */
  public function register() {
   // \add_filter( 'get_user_option_admin_color', [ $this, 'set_admin_color' ], 10, 0 );

    //\remove_action('woocommerce_single_product_summary', 'woocommerce_template_single_excerpt', 20); 
    //\add_action('woocommerce_after_add_to_cart_form', 'woocommerce_template_single_excerpt');
  }
}

SORRY I forgot composer dumpautoload.... It is ok...

**Comment by IvanGrginovInf** [comment]
> SORRY I forgot composer dumpautoload.... It is ok...

@marijang So all is well? :)

**Comment by marijang** [comment]
Yes

**Comment by iruzevic** [comment]
Awesome

**Comment by marijang** [comment]
DO you have lib for form elements? (CSS)

**Comment by IvanGrginovInf** [comment]
@marijang we have https://github.com/infinum/eightshift-forms but it's not yet ready (should be soon™).

**Comment by marijang** [comment]
Cool
