### ISSUE TITLE
Block editor

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-boilerplate#225]
How to import svg from block editor?

I put svg into image and added import into index.js
so svg is public dir now

Thanks

**Comment by iruzevic** [comment]
You want to import svg file from public folder to Gutenberg block, React part?

**Comment by marijang** [comment]
Public folder

**Comment by marijang** [comment]
yes, react part

**Comment by iruzevic** [comment]
The problem with that is that React expect the svg to be in a format that is valid in JSX. Alos. it can't import html to a prop because that is not safe.

I suggest to just copy the full svg code in the React component and it should work with some tweaking.

here is one of my components for example:
```jsx
import React from 'react'; // eslint-disable-line no-unused-vars
import classnames from 'classnames';
import { Fragment } from '@wordpress/element';

export const CarouselNavigation = (attributes) => {
	const {
		componentClass = 'carousel-navigation',
		selectorClass = componentClass,
		blockClass,
		jsPrevClass,
		jsNextClass,
		theme = 'default',
	} = attributes;

	const navigationlass = classnames(
		componentClass,
		theme ? `${componentClass}__theme--${theme}` : '',
		blockClass && `${blockClass}__${selectorClass}`,
	);

	const prevClass = classnames(
		`${componentClass}__item`,
		`${componentClass}__item--prev`,
		jsPrevClass
	);

	const nextClass = classnames(
		`${componentClass}__item`,
		`${componentClass}__item--next`,
		jsNextClass
	);

	const iconClass = classnames(`${componentClass}__icon`);

	return (
		<Fragment>
			<div className={navigationlass}>
				<div className={prevClass}>
					<svg className={iconClass} width="22" height="40" xmlns="http://www.w3.org/2000/svg">
						<g style="mix-blend-mode:multiply" stroke="#FFF" fill="none" fillRule="evenodd" strokeLinecap="round">
							<path d="M1 20L21 1M21 39L1 20" />
						</g>
					</svg>
				</div>
				<div className={nextClass}>
					<svg className={iconClass} width="22" height="40" xmlns="http://www.w3.org/2000/svg">
						<g style="mix-blend-mode:multiply" stroke="#FFF" fill="none" fillRule="evenodd" strokeLinecap="round">
							<path d="M21 20L1 1M1 39l20-19" />
						</g>
					</svg>
				</div>
			</div>
		</Fragment>
	);
};
```

**Comment by marijang** [comment]
and what if i want to add from php template?

use get_template_part?

**Comment by iruzevic** [comment]
Not sure about that I think you can't fetch files that are not php with `get_template_part` function.

We are working on a new release, so we have something like this. Here is a link how we are fetching manifest.json file inside of php files. so maybe this will help:

https://github.com/infinum/eightshift-libs/blob/57498081cb1fa8c3021d2aa943ac51d2b6801ade/src/Helpers/Components.php#L125

**Comment by gabriel-glo** [comment]
You would have to create a PHP template for each SVG image to use `get_template_part`. You should be able to just c/p SVG markup into this PHP template without any modifications.

Otherwise, you can use the method for getting file URL from the manifest and put that URL in `img` element.
