### ISSUE TITLE
Escaping will strip out the meta tags

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#237]
https://github.com/infinum/eightshift-boilerplate/blob/11035a2ba219030166c55db90fb6a1331ccff654/header.php#L18

Either `meta` needs to be in the kses filter or this escaping needs to be removed.

Escaping strips all the meta tags, and the responsive is not working at all.

**Comment by iruzevic** [comment]
I think we. can remove it? @dingo-d agree?

**Comment by iruzevic** [comment]
made a PR
