### ISSUE TITLE
a11y - add "skip to main" button

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-boilerplate#255]
### Describe your feature request

Users using screen readers probably don't want to go trough the header / navigation each time page loads.

### Describe the solution you'd like

To make things easier for them we can add an anchor link right after the `<body>` to skip to the `<main id="main-content">.` Also hide this with .screen-reader-text WP class.

Actually is see now that is a part of WP a11y [handbook](https://make.wordpress.org/accessibility/handbook/markup/skip-links/) and we could use their [__Good practice__](https://make.wordpress.org/accessibility/handbook/markup/skip-links/#good-practice) as a guide.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by mbmjertan** [comment]
I'll close this, as a skip link component already exists in Frontend Libs! https://github.com/infinum/eightshift-frontend-libs/tree/develop/blocks/init/src/Blocks/components/skip-link

It's not part of the default theme, as we already are WCAG compliant without it (by using other techniques to provide ways to skip repeated content, such as ARIA landmarks). 

This is part of the WCAG Success Criterion 2.4.1. Bypass Blocks, and you can see more context regarding why this isn't part of the default theme, as well as what development work is required to support this in your theme in the component readme.

Feel free to hit me up if you need any help / clarification regarding this.
