### ISSUE TITLE
Refresh the default readme

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-boilerplate#260]
### Describe your feature request

I think the readme should be a bit more polished.

At the very least having the `npx` command and the requirements should be added (explicitly, without just linking to the docs).

The link to the documentation should be present (as it is now).

A big chunk of the readme serves no purpose. Like the features part.

We can make it more concise. I think that could encourage more people to start using it without going through all the documentation first.

Also, we should remove all the references to the Eightshift website...

### Describe the solution you'd like

Rewrite the readme

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
this is done
