### ISSUE TITLE
[npm start] failed on boilerplate theme install

### ISSUE THREAD

**Issue by loysbe** [infinum/eightshift-boilerplate#263]
### Describe your bug

I just tried bolierplate for theme : [https://eightshift.com/docs/theme/] (https://eightshift.com/docs/theme/)
Everything was ok until I run "npm start" 
Got the following error

> @eightshift/dev-theme-2@1.0.0 start
> webpack --progress --watch --mode development

[webpack-cli] Error [BrowserslistError]: Unknown version 64 of op_mob
    at Function.select (C:\Users\xxx\OneDrive\Dev\web\Développements\wordpress\wp-content\themes\dev-theme-2\node_modules\browserslist\index.js:1096:17)
    at C:\Users\xxx\OneDrive\Dev\web\Développements\wordpress\wp-content\themes\dev-theme-2\node_modules\browserslist\index.js:314:29
    at Array.reduce (<anonymous>)
    at C:\Users\xxx\OneDrive\Dev\web\Développements\wordpress\wp-content\themes\dev-theme-2\node_modules\webpack\lib\config\defaults.js:132:10
    at F (C:\Users\xxx\OneDrive\Dev\web\Développements\wordpress\wp-content\themes\dev-theme-2\node_modules\webpack\lib\config\defaults.js:73:15)
    at applyWebpackOptionsDefaults (C:\Users\xxx\OneDrive\Dev\web\Développements\wordpress\wp-content\themes\dev-theme-2\node_modules\webpack\lib\config\defaults.js:131:2) {
  browserslist: true

### Steps to Reproduce

- install theme boilerplate from https://eightshift.com/docs/theme/
- run all commands
- run npm start

### Expected behavior

npm start should not fail

### Environment info

windows 11
latest PHP installed with xampp

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by dingo-d** [comment]
In your `.browserslistrc` there is this line which needs to be removed

https://github.com/infinum/eightshift-boilerplate/blob/d78751a56a8d30c0e8caad5d86e477210d78edbe/.browserslistrc#L4

This is a recent deprecation I think.

**Comment by loysbe** [comment]
That was quick ! Thanks a lot.
