### ISSUE TITLE
Class issues

### ISSUE THREAD

**Issue by sternj** [infinum/eightshift-boilerplate#266]
### Describe the question we can answer

Hi all! I'm trying to run Eightshift in a Docker container and, after setting up the site, running `npx create-wp-project`, and activating the theme I created, I'm getting a stack trace that looks like:

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class "Geo\Manifest\Manifest" not found in /var/www/html/wp-content/themes/geo/header.php:21
Stack trace:
#0 /var/www/html/wp-includes/template.php(770): require_once()
#1 /var/www/html/wp-includes/template.php(716): load_template('/var/www/html/w...', true, Array)
#2 /var/www/html/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#3 /var/www/html/wp-content/themes/geo/index.php(9): get_header()
#4 /var/www/html/wp-includes/template-loader.php(106): include('/var/www/html/w...')
#5 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...')
#6 /var/www/html/index.php(17): require('/var/www/html/w...')
#7 {main}
  thrown in /var/www/html/wp-content/themes/geo/header.php on line 21
 ```

### Environment info

I'm working from [dingo-d's boilerplate](https://github.com/dingo-d). [here's my docker-compose.yml](https://gist.github.com/sternj/4e8546c387acad21ab4261947198eb10) and [here's the Dockerfile I'm using for the Wordpress container](https://gist.github.com/sternj/1e3d1d94799f00c9628e292e108a5fe8)

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by dingo-d** [comment]
You can check the following blog post about [setting the theme up](https://eightshift.com/blog/initial-setup). You need to add the necessary classes and run the `npm run build` or `npm start` command in order to generate the `manifest.json` file that points towards the scripts and styles.
