### ISSUE TITLE
Styles and docker-compose

### ISSUE THREAD

**Issue by sternj** [infinum/eightshift-boilerplate#267]
### Describe the question we can answer

Like last time, I've been working on setting up a development (and eventually prod) environment using docker-compose.  I'm completing the setup as per the blog post that dingo-d pointed me to, but I'm not quite getting the styles (see screenshot below). I think this has something to do with me misunderstanding either how the stylesheets are created or how to deal with them in the context of an environment with nginx running in front of it. I've tried running `build` instead of `start` as well. What port or route trickery do I need to do?

I'm seeing some similarity to [this issue](https://github.com/infinum/eightshift-boilerplate/issues/192), I have removed `public`, run `npm run build`, and verified that `application-*.css` is being loaded and appears to be CSS. 

### Screenshots, screen recording, code snippet

![image](https://github.com/infinum/eightshift-boilerplate/assets/19748383/50e83536-4897-466b-8eb0-b5cfd78f76de)

### Environment info

I'm working from [dingo-d's boilerplate](https://github.com/dingo-d). [here's my forked repo](https://github.com/umass-cs-stewards/wordpress-docker)

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by dingo-d** [comment]
Are you running on Mac or Windows when using Docker? 

Mac is known to have issues with syncing the local filesystem changes due to the difference between the filesystems between Docker and Mac.

**Comment by sternj** [comment]
Linux, actually

**Comment by sternj** [comment]
To be more specific, now that I'm back at a shell, I'm running Ubuntu 22.04.1 headless with kernel 5.15.0-72 and Docker v24.0.0 build 98fdcd7

**Comment by dingo-d** [comment]
Well that's odd, Linux should be super fast with Docker :S 

Not 100% sure what could be the case as why it doesn't work tbh, I guess someone from the Eightshift team will check what's the problem :)

**Comment by sternj** [comment]
Yeah I think that I'm missing something architectural, it doesn't seem like there are any requests left outstanding from the browser and I'm wondering if I need to expose another route or port. 

Anyway, if you have anyone who you can ping about this, I would very much appreciate it!

**Comment by iruzevic** [comment]
it sounds like this can be closed
