### ISSUE TITLE
Yoast SEO can't read text

### ISSUE THREAD

**Issue by markoarula** [infinum/eightshift-boilerplate#269]
### Describe your bug

I'm using the Yoast SEO plugin and the plugin can't read text from a paragraph block.
The plugin seems to ignore eighth shift blocks.
<img width="611" alt="image" src="https://github.com/infinum/eightshift-boilerplate/assets/27228538/a43e3fb1-1d8b-4ae1-aab4-2c6b2fad7a72">

### Steps to Reproduce

This happens on all pages, posts and CPTs.

### Expected behavior

I should see no error on text length count, links count and others.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

No

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

No

**Comment by iruzevic** [comment]
Hi, tnx for reaching out.
We have that covered, as Yoast SEO doesn't work with dynamic blocks, We have provided the fix for it.

Find `application-blocks-editor.js` file in your project and add this:
```js
import { yoastSeo } from '@eightshift/frontend-libs/scripts/plugins';

// Seo tool.
yoastSeo();
```

and don't forget to rebuild you assets after it using `npm run build`

**Comment by iruzevic** [comment]
if you want to check more about this function you can find it here

https://github.com/infinum/eightshift-frontend-libs/blob/develop/scripts/plugins/yoast-seo.js

**Comment by markoarula** [comment]
It works perfectly :)
Thank you
