### ISSUE TITLE
Plugin Dev Setup

### ISSUE THREAD

**Issue by robindevitt** [infinum/eightshift-boilerplate#270]
### Describe the question we can answer

Hey there, So I have setup a new project, I seem to have everything working except for being able to run the WP-CLI commands.

Our current folder structure is setup and runs a docker container.

I am able to run WP-CLI commands with the following example:
```
docker exec wpcli wp plugin activate hello
```

The command works, however when I try the following:
```
docker exec wpcli wp boilerplate --help   
```

I get the following error : 
> Error: 'boilerplate' is not a registered wp command. See 'wp help' for available commands.

So it appears that the standard wp-cli commands work for me, but the `boilerplate` doesn't.

Any suggestions?

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
@goranalkovic-infinum can you please check this?

**Comment by dingo-d** [comment]
@robindevitt Is your plugin activated? Because the only reason the command wouldn't work is if the plugin is not active iirc 🤔

**Comment by robindevitt** [comment]
@dingo-d Confirmed that the plugin is active 👍🏼

**Comment by goranalkovic-infinum** [comment]
@robindevitt could you maybe try one more `composer install` just for good measure, and also a `composer dump-autoload`?

**Comment by robindevitt** [comment]
Thanks @goranalkovic-infinum I'll give that a bash.

So I think it's possibly something todo with the way the container is being built and the files are being added from our side.

The plugin is available to be activated via the WordPress Admin area but the plugin isn't showing up when I run `docker exec wpcli wp plugin list` which is starting to make a bit more sense.

I'll post an update once I have it figured out 🤞🏼

**Comment by robindevitt** [comment]
@goranalkovic-infinum I have managed to get this sorted. In the end I have added the volume that was setup for the WordPress Docker Container to the WP-CLI Container we created and that seemed to do the trick 👍🏼 

One other question, is this the correct methods to setting up the Eightshift Coding Standards into VSCode - https://github.com/infinum/eightshift-coding-standards#visual-studio-code ?

**Comment by iruzevic** [comment]
Awesome tnx for the info. Regarding code standards, the best person to ask is @dingo-d because he is the author and a great contributor to the coding standards.

**Comment by dingo-d** [comment]
@robindevitt I think that should still be the correct way to set them up.

Word of advice, we're still blocked on PHP 8 support due to WordPress Coding Standard v3 not being out yet. Once it's out, I'll update and remove the version blocker.

**Comment by robindevitt** [comment]
Thanks @dingo-d

I was initially concerned around the [vscode-phpcs](https://github.com/ikappas/vscode-phpcs/) with no updated for +- 5 years.

 I'll keep my eyes open for the update 👍🏼
