### ISSUE TITLE
Unable to install latest version using npx create-wp-project command

### ISSUE THREAD

**Issue by JerrySpecter** [infinum/eightshift-boilerplate#271]
### Describe the question we can answer

I'm trying to install the latest version of the boilerplate but installation exits on the first step without any error messages.

### Screenshots, screen recording, code snippet

<img width="575" alt="image" src="https://github.com/infinum/eightshift-boilerplate/assets/25869062/82446f3f-19e7-41de-b0de-76cf0c3227fc">

### Environment info

- PHP: 8.2.5
- Laravel Valet
- Node: v18.12.1
- NPM: 8.19.2

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
Not sure but can you try on php7.4. we haven't tested it on pho8

**Comment by goranalkovic-infinum** [comment]
PHP 7.4 works for sure, 8.0 should be fine, but 8.1+ is a no-go.

**Comment by JerrySpecter** [comment]
Yup, downgraded to 8.0 and it works great! Thanks!

**Comment by iruzevic** [comment]
tnx for the issue we have this in the pipeline https://github.com/infinum/eightshift-frontend-libs/issues/677
