### ISSUE TITLE
File loader adds extra hashes to name

### ISSUE THREAD

**Issue by tihomirselak** [infinum/eightshift-boilerplate#96]
## Current Behavior

File loader in webpack is copying some fonts to public folder while adding multiple hashes to name, sometimes after save it adds another duplicate font with one extra hash, it is doing that for icon-fonts from https://icomoon.io on font format .woff

## Expected Behavior

File loader should copy fonts to public folder with one hash added to the name of the font,

## Steps to Reproduce (for bugs)

1. Webpack config for file-loader in rules
```js
// Outputs
const outputJs = 'scripts/[name]-[hash].js';
const outputCss = 'styles/[name]-[hash].css';
const outputFile = '[name]-[hash].[ext]';
const outputImages = images/${outputFile};
const outputFonts = fonts/${outputFile};
```
```js
{
  test: /.(eot|otf|ttf|woff|woff2|svg)$/,
  exclude: [/images/, /node_modules/],
  use: file-loader?name=${outputFonts},
},
```

## Your Environment

* PHP version: 7.2.5-1
* Development environment:  Vagrant
* Server type:  Nginx
* Operating System and version: Ubuntu14.04.1
* Node version: 10.3.0
* NPM version: 6.1.0
* Webpack version: 4.5.0
* File loader version: 1.1.11

**Comment by dingo-d** [comment]
I think that #91 should take care of hashes, not 100% sure about fonts.

If you use 

```js
use: `file-loader?name=${outputFonts}\`,
```

The hashes shouldn't be added to the fonts. If we add hashes to the fonts, those should be picked up by the manifest and then it woulnd't be an issue with using them. 

Will check this out.

**Comment by iruzevic** [comment]
this issue didn't repeat it self so I will say it is fixed
